"""<Insert name of migration>

Revision ID: c833d1333f8d
Revises: e480f7635da9
Create Date: 2021-08-04 00:17:10.743046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c833d1333f8d'
down_revision = 'e480f7635da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('chat', sa.Column('hash_key', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'hash_key')
    op.drop_column('chat', 'name')
    # ### end Alembic commands ###
